image: ghcr.io/vioneta/{arch}-vionetaos-base
build_from:
  aarch64: ghcr.io/home-assistant/aarch64-base-python:3.12-alpine3.19
  armhf: ghcr.io/home-assistant/armhf-base-python:3.12-alpine3.19
  armv7: ghcr.io/home-assistant/armv7-base-python:3.12-alpine3.19
  amd64: ghcr.io/home-assistant/amd64-base-python:3.12-alpine3.19
  i386: ghcr.io/home-assistant/i386-base-python:3.12-alpine3.19
# codenotary:
#   signer: notary@home-assistant.io
#   base_image: notary@home-assistant.io
# cosign:
#   base_identity: https://github.com/home-assistant/docker-base/.*
#   identity: https://github.com/home-assistant/docker/.*
labels:
  io.hass.type: vionetaos-base
  org.opencontainers.image.title: VionetaOS Core baseimage
  org.opencontainers.image.description: Baseimage for VionetaOS Core container/supervisor installation
  org.opencontainers.image.source: https://github.com/Vioneta/docker
  org.opencontainers.image.authors: The VionetaOS Authors
  org.opencontainers.image.url: https://www.vioneta.com/
  org.opencontainers.image.documentation: https://www.vioneta.com/docs/
  org.opencontainers.image.licenses: Apache License 2.0
args:
  SSOCR_VERSION: 2.23.1
  LIBCEC_VERSION: 6.0.2
  TELLDUS_COMMIT: 2598bbed16ffd701f2a07c99582f057a3decbaf3
  PICOTTS_HASH: e3ba46009ee868911fa0b53db672a55f9cc13b1c
